# Generated by Django 3.1.7 on 2021-03-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('match_time', models.DateTimeField()),
                ('base_price', models.PositiveIntegerField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('state', models.PositiveIntegerField(choices=[(1, 'Available'), (2, 'Sold'), (3, 'Outoforder'), (4, 'Expired')], default=1)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketmatch', to='match.match')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketseat', to='stadium.seat')),
            ],
        ),
    ]
