# Generated by Django 3.1.7 on 2021-03-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('row', models.PositiveIntegerField(default=1)),
                ('seats_in_row', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.stadium')),
            ],
        ),
    ]
